apiVersion: bindplane.observiq.com/v1beta
kind: SourceType
metadata:
  name: common_event_format
  displayName: Common Event Format
  icon: /icons/sources/common_event_format.svg
  description: Collect logs from Common Event Formatted log files.
spec:
  version: 0.0.1
  supported_platforms:
    - linux
    - windows
    - macos
  parameters:
    - name: file_log_path
      label: File Path
      description: Specify a single path or multiple paths to read one or many files. You may also use a wildcard (*) to read multiple files within a directory.
      type: strings
      default: []
      required: true

    - name: exclude_file_log_path
      label: Exclude File Path
      description: Specify a single path or multiple paths to exclude one or many files from being read. You may also use a wildcard (*) to exclude multiple files from being read within a directory.
      type: strings
      default: []
      advanced_config: true

    - name: log_type
      label: Type
      description: Adds the specified 'Type' as a log record attribute to each log message.
      type: string
      default: "cef"

    - name: location
      label: Geographic Location
      description: The geographic location (timezone) to use when parsing logs that contain a timestamp
      type: timezone
      default: "UTC"

    - name: timezone
      label: Timezone
      description: The timezone to use when parsing timestamps.
      type: timezone
      default: "UTC"
      advancedConfig: true

    - name: start_at
      label: Start At
      description: Start reading file from 'beginning' or 'end'
      type: enum
      validValues:
        - beginning
        - end
      default: "end"
  
  logs:
    receivers: |
      - plugin/common_event_format:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/common_event_format_logs.yaml
          parameters:
            file_log_path: 
              {{ range $fp := .file_log_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ if .exclude_file_log_path }}
              {{ range $fp := .exclude_file_log_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ end }}
            log_type: {{ .log_type }}
            timezone: {{ .timezone }}
            start_at: {{ .start_at }}
