apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: hana
  displayName: SAP Hana
  icon: /icons/sources/sap.svg
  #description: Collect metrics logs from SAP Hana
  description: Collect logs from SAP Hana
spec:
  version: 0.0.1
  supported_platforms:
    - macos
    - linux
    - windows
  parameters:
    # # Metrics
    # - name: enable_metrics
    #   label: Metrics
    #   type: bool
    #   default: true

    # - name: collection_interval
    #   label: Collection Interval
    #   description: How often (seconds) to scrape for metrics.
    #   type: int
    #   default: 60
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true

    # - name: address
    #   label: Address
    #   description: IP address or hostname to scrape for metrics.
    #   type: string
    #   default: localhost
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true

    # - name: port
    #   label: Port
    #   description: Port to scrape for metrics.
    #   type: int
    #   default: 33015
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true

    # - name: username
    #   label: Username
    #   description: Username used to authenticate.
    #   type: string
    #   required: true
    #   default: ""
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true

    # - name: password
    #   label: Password
    #   description: Password used to authenticate.
    #   type: string
    #   required: true
    #   default: ""
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true

    # - name: enable_tls
    #   label: TLS
    #   type: bool
    #   default: false
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true

    # - name: strict_tls_verify
    #   label: Strict TLS Certificate Verification
    #   description: Enable to require TLS certificate verification.
    #   type: bool
    #   default: false
    #   advancedConfig: true
    #   relevantIf:
    #     - name: enable_metrics
    #       operator: equals
    #       value: true
    #     - name: enable_tls
    #       operator: equals
    #       value: true

    # - name: ca_file
    #   label: TLS Certificate Authority File
    #   description: Certificate authority used to validate TLS certificates. Not required if the collector's operating system already trusts the certificate authority.
    #   type: string
    #   required: false
    #   default: ""
    #   relevantIf:
    #     - name: strict_tls_verify
    #       operator: equals
    #       value: true
    #     - name: enable_metrics
    #       operator: equals
    #       value: true
    #     - name: enable_tls
    #       operator: equals
    #       value: true
    #   advancedConfig: true

    # - name: mutual_tls
    #   label: Mutual TLS Authentication
    #   description: Enable to require TLS mutual authentication.
    #   type: bool
    #   default: false
    #   relevantIf:
    #     - name: strict_tls_verify
    #       operator: equals
    #       value: true
    #     - name: enable_metrics
    #       operator: equals
    #       value: true
    #     - name: enable_tls
    #       operator: equals
    #       value: true
    #   advancedConfig: true

    # - name: cert_file
    #   label: Mutual TLS Client Certificate File
    #   description: A TLS certificate used for client authentication, if mutual TLS is enabled.
    #   type: string
    #   required: true
    #   default: ""
    #   relevantIf:
    #     - name: strict_tls_verify
    #       operator: equals
    #       value: true
    #     - name: mutual_tls
    #       operator: equals
    #       value: true
    #     - name: enable_metrics
    #       operator: equals
    #       value: true
    #     - name: enable_tls
    #       operator: equals
    #       value: true
    #   advancedConfig: true

    # - name: key_file
    #   label: Mutual TLS Client Private Key File
    #   description: A TLS private key used for client authentication, if mutual TLS is enabled.
    #   type: string
    #   required: true
    #   default: ""
    #   relevantIf:
    #     - name: strict_tls_verify
    #       operator: equals
    #       value: true
    #     - name: mutual_tls
    #       operator: equals
    #       value: true
    #     - name: enable_metrics
    #       operator: equals
    #       value: true
    #     - name: enable_tls
    #       operator: equals
    #       value: true
    #   advancedConfig: true

    # Logs
    # - name: enable_logs
    #   label: Logs
    #   type: bool
    #   default: true

    - name: file_path
      label: Log Path(s)
      description: File paths to logs.
      type: strings
      default:
        - "/usr/sap/*/HDB*/*/trace/*.trc"
      required: true
      # relevantIf:
      #   - name: enable_logs
      #     operator: equals
      #     value: true

    - name: timezone
      label: Timezone
      description: The timezone to use when parsing timestamps.
      type: timezone
      default: "UTC"
      advancedConfig: true
      # relevantIf:
      #   - name: enable_logs
      #     operator: equals
      #     value: true

    - name: start_at
      label: Start At
      description: Start reading logs from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      advancedConfig: true
      # relevantIf:
      #   - name: enable_logs
      #     operator: equals
      #     value: true

  # metrics:
  #   receivers: |
  #     {{ if .enable_metrics }}
  #     - saphana:
  #         endpoint: {{ .address }}:{{ .port }}
  #         collection_interval: {{ .collection_interval }}s
  #         username: {{ .username }}
  #         password: {{ .password }}

  #         tls:
  #         {{ if .enable_tls }}
  #           insecure: false
  #           {{ if .strict_tls_verify }}
  #           insecure_skip_verify: false
  #           {{ if .ca_file }}
  #           ca_file: {{ .ca_file }}
  #           {{ end }}
  #           {{ else }}
  #           insecure_skip_verify: true
  #           {{ end }}
  #           {{ if .mutual_tls }}
  #           cert_file: "{{ .cert_file }}"
  #           key_file: "{{ .key_file }}"
  #           {{ end }}
  #         {{ else }}
  #           insecure: true
  #         {{ end }}
  #     {{ end }}

  #   processors: |
  #     - resourcedetection:
  #         detectors: ["system"]
  #         system:
  #           hostname_sources: ["os"]

  logs:
    receivers: |
      - plugin:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/sap_hana_logs.yaml
          parameters:
            start_at: {{ .start_at }}
            timezone: {{ .timezone }}
            file_path:
              {{ range $fp := .file_path }}
              - '{{ $fp }}'
              {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
