apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: tomcat
  displayName: Tomcat
  icon: /icons/sources/tomcat.svg
  description: Collect metrics and logs from Tomcat.
spec:
  version: 0.0.1
  supported_platforms:
    - macos
    - linux
    - windows
  parameters:
    # Metrics
    - name: enable_metrics
      label: Enable Metrics
      type: bool
      default: true

    - name: collection_interval
      label: Collection Interval
      description: How often (seconds) to scrape for metrics.
      type: int
      default: 60
      advancedConfig: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: address
      label: Address
      description: IP address or hostname to scrape for JMX metrics.
      type: string
      default: localhost
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: port
      label: Port
      description: Port to scrape for JMX metrics.
      type: int
      default: 9012
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    - name: jar_path
      label: JMX Metrics Collection Jar Path
      description: Full path to the JMX metrics jar.
      type: string
      default: "/opt/opentelemetry-java-contrib-jmx-metrics.jar"
      advancedConfig: true
      relevantIf:
        - name: enable_metrics
          operator: equals
          value: true

    # Logs
    - name: enable_logs
      label: Enable Logs
      type: bool
      default: true

    - name: enable_access_log
      label: Access Logs
      type: bool
      default: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: access_log_path
      label: Access Log Path(s)
      description: File paths to access logs.
      type: strings
      default:
        - "/usr/local/tomcat/logs/localhost_access_log.*.txt"
      required: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
        - name: enable_access_log
          operator: equals
          value: true

    - name: enable_catalina_log
      label: Catalina Logs
      type: bool
      default: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: catalina_log_path
      label: Catalina Log Path(S)
      description: File paths to catalina logs.
      type: strings
      default:
        - "/usr/local/tomcat/logs/catalina.out"
      required: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true
        - name: enable_catalina_log
          operator: equals
          value: true

    - name: timezone
      label: Timezone
      description: The timezone to use when parsing timestamps.
      type: timezone
      default: "UTC"
      advancedConfig: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

    - name: start_at
      label: Start At
      description: Start reading logs from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      advancedConfig: true
      relevantIf:
        - name: enable_logs
          operator: equals
          value: true

  metrics:
    receivers: |
      {{ if .enable_metrics }}
      - jmx:
          jar_path: {{ .jar_path }}
          collection_interval: {{ .collection_interval }}s
          endpoint: {{ .address }}:{{ .port }}
          target_system: tomcat
          resource_attributes:
            tomcat.endpoint: {{ .address }}:{{ .port }}
      {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]

  logs:
    receivers: |
      {{ if .enable_logs }}
      - plugin:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/tomcat_logs.yaml
          parameters:
            start_at: {{ .start_at }}
            timezone: {{ .timezone }}

            enable_access_log: {{ .enable_access_log }}
            {{ if .enable_access_log }}
            access_log_path:
              {{ range $fp := .access_log_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ end }}

            enable_catalina_log: {{ .enable_catalina_log }}
            {{ if .enable_catalina_log }}
            catalina_log_path:
              {{ range $fp := .catalina_log_path }}
              - '{{ $fp }}'
              {{ end }}
            {{ end }}
      {{ end }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
