apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: ubiquiti
  displayName: Ubiquiti
  icon: /icons/sources/ubiquiti.svg
  description: Receive Syslog from Ubiquiti devices.
spec:
  version: 0.0.1
  supported_platforms:
    - macos
    - linux
    - windows
  parameters:
    - name: listen_port
      label: Listen Port
      description: A UDP port which the agent will listen for syslog messages.
      type: int
      default: 5140

    - name: listen_ip
      label: Listen Address
      description: An IP address for the agent to bind. Typically 0.0.0.0 for most configurations.
      type: string
      default: "0.0.0.0"
      advancedConfig: true

    - name: timezone
      label: Timezone
      description: The timezone to use when parsing timestamps.
      type: timezone
      default: "UTC"
      advancedConfig: true

  logs:
    receivers: |
      - plugin:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/ubiquiti_logs.yaml
          parameters:
            listen_port: {{ .listen_port }}
            listen_ip: {{ .listen_ip }}
            timezone: {{ .timezone }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
