apiVersion: bindplane.observiq.com/v1
kind: SourceType
metadata:
  name: wildfly
  displayName: WildFly
  icon: /icons/sources/wildfly.svg
  description: Collect logs from Wildfly.
spec:
  version: 0.0.1
  supported_platforms:
    - linux
    - windows
  parameters:
    - name: standalone_file_path
      label: Standalone Server File Path(s)
      description: File paths to tail for standalone server logs.
      type: strings
      default:
        - /opt/wildfly/standalone/log/server.log

    - name: enable_domain_server
      label: Domain Server Logs
      description: Enable to read domain server logs.
      type: bool
      default: true

    - name: domain_server_path
      label: Domain Server File Path(s)
      description: File paths to tail for domain server logs.
      type: strings
      default:
        - '/opt/wildfly/domain/servers/*/log/server.log'
      relevantIf:
        - name: enable_domain_server
          operator: equals
          value: true

    - name: enable_domain_controller
      label: Domain Controller Logs
      description: Enable to read domain controller logs.
      type: bool
      default: true

    - name: domain_controller_path
      label: Domain Controller File Path(s)
      description: File paths to tail for domain controller logs.
      type: strings
      default:
        - '/opt/wildfly/domain/log/*.log'
      relevantIf:
        - name: enable_domain_controller
          operator: equals
          value: true

    - name: start_at
      label: Start At
      description: Start reading logs from 'beginning' or 'end'.
      type: enum
      validValues:
        - beginning
        - end
      default: end
      advancedConfig: true

    - name: timezone
      label: Timezone
      description: The timezone to use when parsing timestamps.
      type: timezone
      default: "UTC"
      advancedConfig: true

  logs:
    receivers: |
      - plugin:
          path: $OIQ_OTEL_COLLECTOR_HOME/plugins/wildfly_logs.yaml
          parameters:
            standalone_file_path:
              {{ range $fp := .standalone_file_path }}
              - '{{ $fp }}'
              {{ end }}
            enable_domain_server: {{ .enable_domain_server }}
            domain_server_path:
              {{ range $fp := .domain_server_path }}
              - '{{ $fp }}'
              {{ end }}
            enable_domain_controller: {{ .enable_domain_controller }}
            domain_controller_path:
              {{ range $fp := .domain_controller_path }}
              - '{{ $fp }}'
              {{ end }}
            start_at: {{ .start_at }}
            timezone: {{ .timezone }}

    processors: |
      - resourcedetection:
          detectors: ["system"]
          system:
            hostname_sources: ["os"]
