apiVersion: bindplane.observiq.com/v1beta
kind: ProcessorType
metadata:
  name: add_attribute
  displayName: Add Log Record Attribute
  description: Insert, update, or upsert log record attributes.
spec:
  version: 0.0.1
  parameters:
    - name: action
      label: Action
      type: enum
      description: "insert: Add attribute if it does not exist. update: Update existing value. upsert: Insert or update."
      default: upsert
      validValues:
        - insert
        - update
        - upsert

    - name: attributes
      label: Attributes
      type: map
      required: true

  logs:
    processors: |
      - attributes:
          actions:
            {{ range $k, $v := .attributes }}
            - key: '{{ $k }}'
              value: {{ $v }}
              action: upsert
            {{ end }}
