// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "github.com/observiq/bindplane-op/model"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Versions is an autogenerated mock type for the Versions type
type Versions struct {
	mock.Mock
}

// LatestVersion provides a mock function with given fields:
func (_m *Versions) LatestVersion() (*model.AgentVersion, error) {
	ret := _m.Called()

	var r0 *model.AgentVersion
	if rf, ok := ret.Get(0).(func() *model.AgentVersion); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentVersion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LatestVersionString provides a mock function with given fields:
func (_m *Versions) LatestVersionString() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SyncVersion provides a mock function with given fields: version
func (_m *Versions) SyncVersion(version string) (*model.AgentVersion, error) {
	ret := _m.Called(version)

	var r0 *model.AgentVersion
	if rf, ok := ret.Get(0).(func(string) *model.AgentVersion); ok {
		r0 = rf(version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentVersion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncVersions provides a mock function with given fields:
func (_m *Versions) SyncVersions() ([]*model.AgentVersion, error) {
	ret := _m.Called()

	var r0 []*model.AgentVersion
	if rf, ok := ret.Get(0).(func() []*model.AgentVersion); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AgentVersion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Version provides a mock function with given fields: version
func (_m *Versions) Version(version string) (*model.AgentVersion, error) {
	ret := _m.Called(version)

	var r0 *model.AgentVersion
	if rf, ok := ret.Get(0).(func(string) *model.AgentVersion); ok {
		r0 = rf(version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentVersion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVersions creates a new instance of Versions. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewVersions(t testing.TB) *Versions {
	mock := &Versions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
